version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"  # Проброс порта для фронтенда
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"  # Проброс порта для локальной разработки
    volumes:
      - ./backend:/app
    depends_on:
      - db
    env_file:
      - .env  # Загружаем переменные окружения из файла .env

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: game
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/sql:/docker-entrypoint-initdb.d  # Монтируем SQL-скрипты для инициализации базы

volumes:
  db_data:
    driver: local  # Создаем volume для хранения данных MySQL
